// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umucodliwcdgfzwhlwrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtdWNvZGxpd2NkZ2Z6d2hsd3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MTkwNTAsImV4cCI6MjA2NzE5NTA1MH0.hTurtz-nHDZ1up0e9T7i4_qbziQ4xRVbMerOk-EtK18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});